FROM jenkins/agent:latest as agent

# Switch to the root user to install packages
USER root

# ca-certificates because curl will need it later on for the maven installation
RUN apt-get update && apt-get install -y curl

# Set environment variables for Maven
ENV MAVEN_VERSION 3.8.6
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "/root/.m2"

# Set SHELL flags for RUN commands to allow -e and pipefail
# Rationale: https://github.com/hadolint/hadolint/wiki/DL4006
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

# Add a checksum for the maven binary
RUN curl -sS -L -O --output-dir /tmp/ --create-dirs  https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && printf "%s" "$(sha512sum /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz)" | sha512sum -c - \
    && curl -sS -L -O --output-dir /tmp/ --create-dirs  https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512 \
    && printf "%s /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz" "$(cat /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512)" | sha512sum --check --status - \
    && tar xzf "/tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz" -C  /usr/share \
    && mv /usr/share/apache-maven-${MAVEN_VERSION} ${MAVEN_HOME} \
    && ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn \
    && rm -f "/tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz" \
    && mkdir -p /etc/profile.d \
    && echo "export JAVA_HOME=$JAVA_HOME \n \
             export MAVEN_HOME=/usr/share/maven \n \
             export PATH=${MAVEN_HOME}/bin:${PATH}" > /etc/profile.d/maven.sh

ENV PATH="${MAVEN_HOME}/bin/:${PATH}"

# Ensure the environment variables are set correctly
RUN echo "PATH=${PATH}" >> /etc/environment && mkdir -p /home/jenkins/.ssh  mkdir -p /home/jenkins/.m2 && touch /home/jenkins/.ssh/known_hosts && echo "[gerrit.secuxperdp.com]: 29419 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEfAVScYWifdEL81golNe+YPZCv8Xxgn7UHW/c2b3yB2" >> /home/jenkins/.ssh/known_hosts

# Copy settings.xml to Maven configuration directory
COPY settings.xml /home/jenkins/.m2/settings.xml

# Change ownership of the Jenkins home directory
RUN chown -R jenkins:jenkins /home/jenkins

# Switch back to the jenkins user
USER jenkins
