FROM jenkins/agent:latest as agent

# Switch to the root user to install packages
USER root

ARG NODE_MAJOR=20

# ca-certificates because curl will need it later on for the node installation
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl gnupg && \
    # Installing nodejs
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && apt-get install nodejs -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set SHELL flags for RUN commands to allow -e and pipefail
# Rationale:https://github.com/hadolint/hadolint/wiki/DL4006
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

# Ensure the environment variables are set correctly
RUN echo "PATH=${PATH}" >> /etc/environment

# Set the working directory
WORKDIR /home/jenkins

# Change ownership of the Jenkins home directory
RUN chown -R jenkins:jenkins /home/jenkins

# Switch back to the jenkins user
USER jenkins