pipeline {
    agent { label 'maven' }
    stages {
        stage('Build') {
            steps {
                sh 'echo build step!!!'
            }
        }
        stage('SAST') {
            steps {
                script {
                    def scannerHome = tool name: 'SonarQubeScanner'
                    withSonarQubeEnv() {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }

                }
            }
        }
        stage('Quality Gate') {
            steps {
                script {
                    def qg = waitForQualityGate()
                    if (qg.status != 'OK') {
                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }

}